apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: 2017-08-10T08:52:27Z
    name: llx-nginx
    namespace: default
    resourceVersion: "1046"
    selfLink: /api/v1/namespaces/default/services/llx-nginx
    uid: 3c5819e1-7da9-11e7-8eb6-002590a656c4
  spec:
    clusterIP: 10.107.0.255
    externalTrafficPolicy: Cluster
    ports:
    - nodePort: 30898
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      k8s-app: app-nginx
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: 2017-08-10T08:52:27Z
    generation: 1
    labels:
      k8s-app: app-nginx
      task: task-nginx
    name: llx-nginx
    namespace: default
    resourceVersion: "1076"
    selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/llx-nginx
    uid: 3c3fff42-7da9-11e7-8eb6-002590a656c4
  spec:
    replicas: 2
    selector:
      matchLabels:
        k8s-app: app-nginx
        task: task-nginx
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          k8s-app: app-nginx
          task: task-nginx
      spec:
        containers:
        - image: nginx:latest
          imagePullPolicy: IfNotPresent
          name: llx-nginx
          ports:
          - containerPort: 80
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 2
    conditions:
    - lastTransitionTime: 2017-08-10T08:52:29Z
      lastUpdateTime: 2017-08-10T08:52:29Z
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 1
    readyReplicas: 2
    replicas: 2
    updatedReplicas: 2
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
