apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rls102
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: rls 
        k8s-app: rls102
    spec:
      hostNetwork: true
      nodeSelector:
        role: rls
      containers:
      - name: rls102
        image: rls:alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 30998
          protocol: UDP
        volumeMounts:
        - mountPath: /home/ini
          name: rls102-vol
      volumes:
      - name: rls102-vol
        hostPath:
          path: /root/server/rls
