apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rlsp102
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: rlsp 
        k8s-app: rlsp102
    spec:
      nodeSelector:
        role: rlsp
      containers:
      - name: rlsp102
        image: rlsp-alpine:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 30818
          protocol: UDP
        - containerPort: 30818
          protocol: TCP
        volumeMounts:
        - mountPath: /home/ini
          name: rlsp102-vol
      volumes:
      - name: rlsp102-vol
        hostPath:
          path: /root/server/rlsp
---
apiVersion: v1
kind: Service
metadata:
  labels:
  name: rlsp102
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 30818
    nodePort: 30818
    protocol: UDP
    name: internal
  - port: 80
    targetPort: 30818
    nodePort: 30818
    protocol: TCP
    name: external
  selector:
    k8s-app: rlsp102
