apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2017-08-17T09:09:39Z
  generation: 1
  labels:
    app: initnginx
  name: initnginx
  namespace: default
  resourceVersion: "26415"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/initnginx
  uid: cc9ff69e-832b-11e7-936d-002590a656c4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: initnginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/init-containers: '[{"name":"install","image":"busybox","command":["/bin/sh","-c","echo
          bar \u003e /work-dir/index.html"],"resources":{},"volumeMounts":[{"name":"workdir","mountPath":"/work-dir"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}]'
        pod.beta.kubernetes.io/init-containers: '[{"name":"install","image":"busybox","command":["/bin/sh","-c","echo
          bar \u003e /work-dir/index.html"],"resources":{},"volumeMounts":[{"name":"workdir","mountPath":"/work-dir"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}]'
      creationTimestamp: null
      labels:
        app: initnginx
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: initnginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: workdir
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - /bin/sh
        - -c
        - echo bar > /work-dir/index.html
        image: busybox
        imagePullPolicy: IfNotPresent
        name: install
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /work-dir
          name: workdir
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          sizeLimit: "0"
        name: workdir
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: 2017-08-17T09:09:42Z
    lastUpdateTime: 2017-08-17T09:09:42Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
