 apiVersion: v1
 kind: PersistentVolume
 metadata:
   name: pv0001
 spec:
   capacity:
     storage: 10Gi
   accessModes:
     - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: slow
   nfs:
     path: /opt/nfs/1
     server: 192.168.1.232
     readOnly: false
