apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: myfrontend
      image: nginx
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: "/var/www/html"
          name: mynfs 
  volumes:
    - name: mynfs
      persistentVolumeClaim:
        claimName: mypvc
