 apiVersion: v1
 kind: PersistentVolume
 metadata:
   name: pv0000
 spec:
   capacity:
     storage: 20Gi
   accessModes:
     - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: slow
   nfs:
     path: /opt/nfs
     server: 192.168.1.232
     readOnly: false
