 apiVersion: v1
 kind: PersistentVolume
 metadata:
   name: pv0003
   annotations:
     volume.beta.kubernetes.io/storage-class: "anything"
 spec:
   capacity:
     storage: 5Gi
   accessModes:
     - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   nfs:
     path: /opt/nfs
     server: 192.168.1.232
     readOnly: false
